### ISSUE TITLE
ERROR CRITIC

### ISSUE THREAD

**Issue by Widsithe** [langeletti/MyGreatProject#2]
**Describe the bug**
ça ne fonctionne pas

**To Reproduce**
J'ai essayé de cliqué, et ça ne marche pas. 

**Expected behavior**
Ça doit marcher.

**Screenshots**
Qu'est ce que c'est ? 

**Desktop (please complete the following information):**
Windows.

**Smartphone (please complete the following information):**
06 36 25 85 74

**Additional context**
**URGENT !!!!**
@viviendel 
@langeletti

**Comment by Widsithe** [comment]
MERCI DE REPARER LE SOUCIS RAPIDEMENT !

**Comment by viviendel** [comment]
Merci de votre retour.
Nous allons prendre cela en compte.
Voir avec  M. @langeletti

**Comment by Widsithe** [comment]
@langeletti Merci de votre réponse RAPIDE

**Comment by langeletti** [comment]
Bonjour Marine,
Bonjour Vivien.

J'ai effectivement rencontré le même problème.
Une solution existe, veuillez suivre pas à pas le tutoriel suivant :

git flush -u
.gif gg

N'hésitez pas à me recontacter si besoin est.

Très cordialement.

**Comment by Widsithe** [comment]
Cher Louis, 

Mille merci, tout fonctionne. 

C'est parfait. 

Bisous.

**Comment by ledarch** [comment]
On m'voit, on m'voit plus, on m'voit un peu..

**Comment by viviendel** [comment]
Merci de votre retour.
Nous allons prendre cela en compte.
